version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: audit_postgres
    environment:
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
      POSTGRES_DB: auditdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit"]
      interval: 2s
      retries: 10
      start_period: 5s

  backend:
    build: ./backend
    container_name: audit_backend
    environment:
      DATABASE_URL: postgresql://audit:audit@postgres:5432/auditdb
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: audit_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
